# Generated by Django 3.0.5 on 2020-05-07 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.CharField(max_length=25)),
                ('donate_address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('slot_time', models.CharField(max_length=20)),
                ('organisation_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=50)),
                ('no_packets', models.IntegerField(default=0)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('request_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
